#! /bin/bash

FLAG=$1;
PATH_ABSOLUT=$PWD/$2;
FILE_TYPE=$3;
readonly MIN_FILE_TMP_CSS=/tmp/main.min.css;
readonly MIN_FILE_TMP_JS=/tmp/main.min.js;

#Verifica se é uma flag (opção) válida.
if echo $FLAG | grep -v '[rio]' &> /dev/null; then
   echo "";
   echo "Você precisa passar uma opção válida:"
   echo "";
   echo "-r --read - Somente ler: Não modifica o arquivo, transforma a saída e cria um novo arquivo.";
   echo "-o --output - Mostra a saída: Não cria nenhum arquivo, só ler o arquivo original, transforma e mostar a saída.";
   echo "-i --in-replace - Substitui: Altera o arquivo, substituindo o texto original pelo transformado.";
   echo "";
   echo "Obs: -i opção só funciona com arquivos especificados: dist/css/header.css, por exemplo."
   echo "";

   exit 0;
fi

# Verifica se o tipo de arquivo a ser minificado está presente.
if [ -d $PATH_ABSOLUT ] 
   then
    if [[ -z $FILE_TYPE ]] 
        then
          echo "";
          echo "css | js";
          echo "Você deve passar a extensão do tipo de arquivo a ser minificado:";
          echo "minify $1 $2 <?>";
          echo "";
          exit 0;
    fi
    FILE_TYPE=".$FILE_TYPE";
else
   FILE_TYPE=`echo "$PATH_ABSOLUT" | grep -o '[.].*'`;
fi

minify-specific-js(){
    FILE_TMP=$1;
    sed -i -e \
        's/= /=/g' -e \
        's/ =/=/g' -e \
        's/== /==/g' -e \
        's/ ==/==/g' -e \
        's/=> /=>/g' -e \
        's/ =>/=>/g' -e \
        's/ +=/+=/g' -e \
        's/+= /+=/g' -e \
        's/-= /-=/g' -e \
        's/ -=/-=/g' -e \
        's/( /(/g' -e \
        's/ (/(/g' -e \
        's/ \/ /\//g' $FILE_TMP;
}

# Suprime todos os espaços redundantes dos arquivos .css e redireciona.
concat_and_minify(){
    FILE_TMP=$1
    scan_dir='';

    if [ -d $PATH_ABSOLUT ]
        then
          scan_dir=`ls $PATH_ABSOLUT/*$FILE_TYPE`;
        else
          scan_dir=`ls $PATH_ABSOLUT`;
    fi

    for file in $scan_dir; 
       do
        # Remove comentários inline | Suprime espaços >> redireciona a saída.
        sed '/^\/.*[\/$]/d' "$file" | tr -s '[:space:]' ' ' >> $FILE_TMP;
    done

    minify_main_complet $FILE_TMP;
};

# Termina o trabalho de minificação, removendo espaços específicos.
minify_main_complet(){
    FILE_TMP=$1;
    sed -i -e \
        's/ {/{/g' -e \
        's/{ /{/g' -e \
        's/ } /}/g' -e \
        's/ }/}/g' -e \
        's/} /}/g' -e \
        's/: /:/g' -e \
        's/; /;/g' -e \
        's/, /,/g' -e \
        's/ > />/g' -e \
        's/ # /#/g' -e \
        's/ \/ /\//g' $FILE_TMP;

        if echo $FILE_TYPE | grep -c '\.js' &> /dev/null; then
           minify-specific-js "$FILE_TMP";
        fi
};

# Verifica se já existe o mesmo arquivo css minificado. Se sim, apaga.
verify_file_exist_and_remove(){
    if [ -f $1 ] 
    then
       rm -rf $1;
    fi
}

# Verifica se já existe o mesmo arquivo css minificado. Se sim, apaga.
if echo $FILE_TYPE | grep -c '\.css' &> /dev/null; then
    verify_file_exist_and_remove "$PATH_ABSOLUT/main.min.css";
    concat_and_minify "$MIN_FILE_TMP_CSS";
fi

# Verifica se já existe o mesmo arquivo js minificado. Se sim, apaga.
if echo $FILE_TYPE | grep -c '\.js' &> /dev/null; then
    verify_file_exist_and_remove "$PATH_ABSOLUT/main.min.js";
    concat_and_minify "$MIN_FILE_TMP_JS";
fi

# Verifica se é um caminho de arquivo e faz tratamento para arquivo;
if [ -f $PATH_ABSOLUT ]; then 

    if echo $FLAG | grep -c '\-r' &> /dev/null; then
       file_name=`echo "$PATH_ABSOLUT" | grep -o '[a-z/].*\.'`;
       min="min";
       mv $FILE_TMP $file_name$min$FILE_TYPE;
    fi  

    if echo $FLAG | grep -c '\-i' &> /dev/null; then
       mv $FILE_TMP $PATH_ABSOLUT;
    fi 
    
    if echo $FLAG | grep -c '\-o' &> /dev/null; then
       cat $FILE_TMP;
    fi

fi

# Verifica se é um diretório e faz tratamento para diretório;
if [ -d $PATH_ABSOLUT ]; then 

    if echo $FLAG | grep -c '\-r' &> /dev/null; then
       mv $FILE_TMP "$PATH_ABSOLUT/main.min$FILE_TYPE";
    fi  
    
    if echo $FLAG | grep -c '\-o' &> /dev/null; then
       cat $FILE_TMP;
    fi

fi
    
rm -rf $FILE_TMP;
unset PATH_ABSOLUT;
unset FILE_TYPE;
unset FILE_RESULT;